### ISSUE TITLE
Doubt on using the beamer

### ISSUE THREAD

**Issue by luis-reyes1985** [pazz/beamerthemeEdinburgh#1]
Hello, I'm new on the Latex world, so I'm not sure what I've done wrong with this beamer. I already uploaded it to overleaf, and I tried to place the  '\usetheme{Edinburgh}' in the preamble. Honestly, I don't really know exactly where the preamble would be, or if I included that piece of code in the right place. Would it be possible for you to review it, please? I can share with you the project that I created in overleaf. Thanks in advande.

**Comment by patricktotzke** [comment]
You need to copy the sty files from this repository close to your source files.
Please refer to https://en.wikibooks.org/wiki/LaTeX/Presentations#Style
and the beamer docs for more info on how to use theme files.
